version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - locallbc-net
    environment:
      - spring.datasource.url=jdbc:mysql://database:3307/lbcfizzbuzz?createDatabaseIfNotExist=true
      - spring.datasource.username=mysql_user
      - spring.datasource.password=mysql_pw
      - springdoc.swagger-ui.path=/swagger-ui.html
      - spring.jpa.hibernate.ddl-auto=create
    depends_on:
      - database
      
  database:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3307
    networks:
      - locallbc-net  
    environment:
      MYSQL_DATABASE: lbcfizzbuzz
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pw
      MYSQL_ROOT_PASSWORD: mysql_rootpw
      MYSQL_TCP_PORT: 3307
networks:
  locallbc-net: